### ISSUE TITLE
[Signal] Receive messages?

### ISSUE THREAD

**Issue by andriej** [haberda/hassio_addons#15]
Would it be possible for addon to receive/parse received messages/actions and publish event from that (or at least MQTT message with json - 'from' and 'message'?)

I can see that -cli is able to receive messages, although it's far from user friendly to do that into HA.

**Comment by haberda** [comment]
This is just a repacked version of a docker container by @bbernhard found [here](https://github.com/bbernhard/signal-cli-rest-api). 

According to the docs from that container it can receive messages, but I don't know how it works. There is an [end point](https://bbernhard.github.io/signal-cli-rest-api/) listed for receiving messages but I don't believe the Home Assistant integration that works with this container has the capability to receive at this point (as far as I can tell [here](https://github.com/home-assistant/core/tree/dev/homeassistant/components/signal_messenger)), so you would probably have to do it outside of HASS.

I think @bbernhard owns the HASS integration as well, so it might be good to put in a feature request over on either the HASS repo or @bbernhard's repo.

**Comment by bbernhard** [comment]
As @haberda already mentioned, there's an API endpoint to receive messages (see the swagger documentation [here](https://bbernhard.github.io/signal-cli-rest-api/) for details). Unfortunately, receiving messages is not yet integrated into the Home Assistant integration. 

But what you can do is to use the REST integration (see https://www.home-assistant.io/integrations/rest/) to call the receive API endpoint and then parse the returned json via a value template.

**Comment by andriej** [comment]
Thanks for the instructions! I was lacking any link to them on the repos, maybe it's worth adding it to readme?
Having it for sure makes it easier for rest to receive and parse messages

**Comment by bbernhard** [comment]
> Thanks for the instructions! I was lacking any link to them on the repos, maybe it's worth adding it to readme?
> Having it for sure makes it easier for rest to receive and parse messages

Definitely! There's a bit of documentation [here](https://github.com/bbernhard/signal-cli-rest-api/blob/master/doc/HOMEASSISTANT.md), but it's not that much. In case you are missing something that would be helpful for beginners, feel free to create a pull request. For me as a developer it's always a bit hard to find those spots where the documentation is lacking/incomplete. So if you stumble across something that could need some additional explanation, I would be really grateful, if you could create a pull request.

**Comment by andriej** [comment]
PR done, can close this one. Thanks :)
