### ISSUE TITLE
Show swagger as Signal add-on's UI

### ISSUE THREAD

**Issue by mdegat01** [haberda/hassio_addons#18]
### Feature Request

The curl requests make it a bit challenging to get going with your add-on currently. Not impossible by any means since its mostly just copy and paste (although I did have to go hunting around in the [issues](https://github.com/bbernhard/signal-cli-rest-api/issues/19) for instructions on how to deal with the captcha). And then afterwards I was hoping to just try it out by making and deleting some groups, sending some messages, etc. and was looking for a faster way to do so then writing out `curl` requests or restarting HA with new REST commands or notify RESTS.

When I came across [the swagger spec](https://bbernhard.github.io/signal-cli-rest-api/#/) I realized you already had a great answer. The add-on could just show that exact web page as the UI for the add-on but with the base URL set to HA's `internal_url`, instead of `127.0.0.1` which is only accessible when executing commands literally from that machine. Could do this as either ingress UI or as a separate webpage, either way would allow for a lot quicker testing/trying out in my opinion.

Just a thought, not sure how difficult it is. I may look into it myself this weekend if I get some time although I have never really worked on an add-on before. Another alternative would be a downloadable [postman collection](https://www.postman.com/collection/) from the readme if adding a UI is harder then I'm giving it credit for.

Either way, thanks for the great add-on!  Really useful.

**Comment by haberda** [comment]
Hmm, yeah I like this idea. I've struggled with getting the correct REST syntax.

I have no idea really how to do this though. I'm not really a developer, I work in physics, so I can write some code, but I don't really know how to implement something like this. I haven't even been able to figure out how to get ingress working on any of my add-ons either, despite trying to copy other's config files.

The current add-on is just repacked from the upstream, all that I did was point the config file storage to the /data folder and change some permissions which HASSIO uses to store add-on data. In fact, that's what all these add-ons are in this repo.

I'll look into it a little, but it's probably beyond my abilities.

**Comment by mdegat01** [comment]
No worries, I understand. I've got some free time this weekend so I might take a stab at it. I've done plenty of coding just never anything with add-ons before.

**Comment by haberda** [comment]
The add-on space isn't hard to work with. It's just fitting the docker container to a template. The documentation isn't great. The first one I figured out how to do was Signal. I was a heavy user of Signal prior to HA supporting it, so I was happy to have the support, but the lack of an add-on was limiting.

The files in this git repo are all there is to it. For any container, all you really have to do is make sure the persistent storage points to /data and then make a config.yaml that has the options you need. I've played with the bashio config stuff to have yaml configs, but it's pretty hard to use when just repackaging someone else's container because the bashio dependencies are usually not installed.

What you are suggesting here is a significant change to @bbernhard's container, which is fine, but it makes is that much more difficult to maintain. I am willing to merge any changes if you get a PR going and will maintain to the best of my ability.

**Comment by mdegat01** [comment]
That makes a lot of sense and also makes me think this is not the right approach. I definitely did not intend to make this add-on harder for you to maintain, strapping some swagger UI to it is not worth the hassle it sounds like that would introduce.

In that case, I think I might have a better idea. Starting in Swagger 3.0 (or really OpenAPI 3.0 now) `baseUrl` is replaced with [servers](https://swagger.io/specification/#server-object) and those allow you to use variables. What that means is that I can basically make baseURL an input box at the top which defaults to `http://127.0.0.1:8080` but allows users to change that and point it at wherever they hosted the Signal REST API. I think with that I could make it so the swagger UI in the repo itself is basically just a user-interface for the add-on.

Or at the very least it generates dynamic, copy-and-pasteable curl commands specific to your setup. Not sure if it can actually be live due to CORS+mixed HTTP/HTTPS issues but still I think that would help. And wouldn't require significantly deviating the add-on from the base container.

**Comment by mdegat01** [comment]
Ok nvm, the swagger is being generated from swaggo so tweaking isn't an option. I'm just going to do a PR to document the captcha option and move on lol.
