### ISSUE TITLE
All APIs breaking on latest version of Signal add-on

### ISSUE THREAD

**Issue by mdegat01** [haberda/hassio_addons#19]
Just updated to the latest version of the Signal add-on and now any API I try returns a response like this:
```json
{
    "error": "WARN App - WARNING: Support for new group V2 is disabled, because the required native library dependency is missing: libzkgroup\nERROR App - Missing required native library dependency: libsignal-client\n"
}
```
I was actually trying to update the profile to be V2 ready when I first received this but I'm getting it from every API, including just trying to send out a message like I used to.

Any ideas what is going on? I tried restarting and rebuilding the addon from supervisor UI but nothing seemed to change this.

**Comment by mdegat01** [comment]
Ok wow, I restored my backup of the addon from yesterday and still nothing is working. It's also not the phone number either, I can't register new numbers now. The only APIs that work for me are the basic health check ones like `/v1/about` and `/v1/configuration`, everything else fails with that error message. I even tried uninstalling and reinstalling and that didn't change anything either.

I have no idea how this happened but any help is appreciated, I really want to get this addon back working as I rely on it a fair amount.

**Comment by tsetzekorn** [comment]
I have exactly the same issue. It was working yesterday, but today I recognized it stopped working with that error message.

**Comment by mdegat01** [comment]
@tsetzekorn were you able to fix it with a rollback or are you still on 0.35? I don't really understand how I'm still seeing this after rollback to 0.34 from my backup. I can confirm it definitely worked fine less then 24 hours ago, I got a message from it.

**Comment by tsetzekorn** [comment]
Same with me. I just did a rollback to a snapshot 4 days ago (release 0.34) and I am again getting the same error. Last successful messages received that I can remember are from yesterday about 17:30 (CET).

Example: /v1/receive/ request with Postman:
{
    "error": "WARN App - WARNING: Support for new group V2 is disabled, because the required native library dependency is missing: libzkgroup\nERROR App - Missing required native library dependency: libsignal-client\n"
}

**Comment by haberda** [comment]
What processor architecture are you using (e.g. ARM, x86)? 

The way this add-on works is it pulls from whatever the dockerfile in the repo here is pointed to, so a rollback of your snapshot won't fix it. I can roll back the add-on and if you press the rebuild button it will rebuild it with 0.34.

0.35 works fine for me on x86, I don't have and ARM setup to test on. By the time you read this I will roll it back, so just press the rebuild button and it should start working again. But I'd like to troubleshoot why it's not working besides that.

**Comment by tsetzekorn** [comment]
I am indeed on a Raspberry Pi, so it is ARM64.

**Comment by haberda** [comment]
Ok, I rolled back the config to 0.34 so hassio should recognize the downgrade. Go to the 'Add-on Store' tab. On the top right there is a pop out menu with a reload option. This will force hassio to reload the repository information. I don't know how it works under the hood exactly, so it's possible that just pressing rebuild uses the cached dockerfile rather than checking the repo.

To include the container dev:
@bbernhard it looks like there is an issue with the ARM64 0.35 container not having the libsignal-client library. I looked at the upstream signal-cli and it looks like 0.8.0 requires this library. My x86 instance does not have an issue.

**Comment by mdegat01** [comment]
> Ok, I rolled back the config to 0.34 so hassio should recognize the downgrade. Go to the 'Add-on Store' tab. On the top right there is a pop out menu with a reload option. This will force hassio to reload the repository information. I don't know how it works under the hood exactly, so it's possible that just pressing rebuild uses the cached dockerfile rather than checking the repo.

Yep this worked, everything is operational again. Should I leave this open for discussion on how to get to 0.35 or should that move to a different issue?

**Comment by tsetzekorn** [comment]
OK, downgrade worked well and after rebuild it is working again. :)

**Comment by haberda** [comment]
Yeah, leave it open for now. Want to get input from the upstream dev. Glad
it works again.

**Comment by bbernhard** [comment]
I think I've found the issue. Unfortunately, I do not own a device with an arm64 architecture, so I was only able to test the image on my x86-64 machine by emulation arm64. Does the Home Assistant addon system have any possibility to test images? (e.g I could push an image to dockerhub with a `dev` tag) Otherwise, I am afraid the only thing I can do is to push the image to production and hope for the best.

**Comment by mdegat01** [comment]
> I think I've found the issue. Unfortunately, I do not own a device with an arm64 architecture, so I was only able to test the image on my x86-64 machine by emulation arm64. Does the Home Assistant addon system have any possibility to test images? (e.g I could push an image to dockerhub with a `dev` tag) Otherwise, I am afraid the only thing I can do is to push the image to production and hope for the best.

I'm not aware of a way to subscribe to a beta/dev channel for an existing addon like I can in the google play store for instance. Although there are a lot of addons that publish two versions of the addon, one that is the stable version and the other that is the beta version. Then the addon changes its setup to either build off a different git branch (ex. [zigbee2mqtt](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/blob/master/common/Dockerfile)) or use a different dockerfile (ex. [room-assistant](https://github.com/mKeRix/room-assistant/blob/master/dev.Dockerfile)).

Another option seems like it could be adding a config option to the addon although I haven't really seen anyone do that before (not really sure why though). Can the `FROM` command in a dockerfile be dynamic based on the config? So like change [this line](https://github.com/haberda/hassio_addons/blob/master/signal/Dockerfile#L1) to start from one base image or another based on the value of a config. Not sure if that's allowed though, I'm not really an expert in docker.

**Comment by bbernhard** [comment]
> > I think I've found the issue. Unfortunately, I do not own a device with an arm64 architecture, so I was only able to test the image on my x86-64 machine by emulation arm64. Does the Home Assistant addon system have any possibility to test images? (e.g I could push an image to dockerhub with a `dev` tag) Otherwise, I am afraid the only thing I can do is to push the image to production and hope for the best.
> 
> I'm not aware of a way to subscribe to a beta/dev channel for an existing addon like I can in the google play store for instance. Although there are a lot of addons that publish two versions of the addon, one that is the stable version and the other that is the beta version. Then the addon changes its setup to either build off a different git branch (ex. [zigbee2mqtt](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/blob/master/common/Dockerfile)) or use a different dockerfile (ex. [room-assistant](https://github.com/mKeRix/room-assistant/blob/master/dev.Dockerfile)).
> 
> Another option seems like it could be adding a config option to the addon although I haven't really seen anyone do that before (not really sure why though). Can the `FROM` command in a dockerfile be dynamic based on the config? So like change [this line](https://github.com/haberda/hassio_addons/blob/master/signal/Dockerfile#L1) to start from one base image or another based on the value of a config. Not sure if that's allowed though, I'm not really an expert in docker.

I am already having two tags, there's the `bbernhard/signal-cli-rest-api:latest` tag which always points to the latest stable docker image on dockerhub and there's the `bbernhard/signal-cli-rest-api:latest-dev` tag which points to the latest dev image on dockerhub. If someone uses the "usual" docker environment, it's usually not a problem to tell them to temporarily switch to the `dev` version to check whether that fixes the issue. But I am not sure how the Home Assistant addon system works. Is there a way to (temporarily) switch to a dev version?

**Comment by mdegat01** [comment]
I might have an idea. If I'm reading [this](https://developers.home-assistant.io/docs/add-ons/testing) correctly I can test a local addon by just sticking all the files in my `/addons` folder. So I'm going to try and clone this repo into that folder and then tweak the `FROM` line at the top of the dockerfile

**Comment by mdegat01** [comment]
@bbernhard Ok well I think I got it working. I'm seeing my local addon and if I look in portainer a new image is now appearing for `bbernhard/signal-cli-rest-api:latest-dev`. But I am still seeing the error so next I want to check if I'm actually running on the latest dev or if my new addon is still running on the stable and I messed something up. Is there something I can look for within the image?

Also I looked at [bbernhard/signal-cli-rest-api on dockerhub](https://hub.docker.com/r/bbernhard/signal-cli-rest-api/tags?page=1&ordering=last_updated) and it says the [latest-dev tag](https://hub.docker.com/layers/bbernhard/signal-cli-rest-api/latest-dev/images/sha256-8e7b9bee2dc18efc4df2c0baa6fa9470db1098d06ec22fd261c0184cd2f3f0f6?context=explore) was last updated 5 days ago. Is there something pending i have to wait for?

**Comment by bbernhard** [comment]
> @bbernhard Ok well I think I got it working. I'm seeing my local addon and if I look in portainer a new image is now appearing for `bbernhard/signal-cli-rest-api:latest-dev`. But I am still seeing the error so next I want to check if I'm actually running on the latest dev or if my new addon is still running on the stable and I messed something up. Is there something I can look for within the image?
> 
> Also I looked at [bbernhard/signal-cli-rest-api on dockerhub](https://hub.docker.com/r/bbernhard/signal-cli-rest-api/tags?page=1&ordering=last_updated) and it says the [latest-dev tag](https://hub.docker.com/layers/bbernhard/signal-cli-rest-api/latest-dev/images/sha256-8e7b9bee2dc18efc4df2c0baa6fa9470db1098d06ec22fd261c0184cd2f3f0f6?context=explore) was last updated 5 days ago. Is there something pending i have to wait for?

I haven't triggered a build yet, because I wasn't sure if anyone is able to test it. But I can kick off a build now.

**Comment by bbernhard** [comment]
Build is now running: https://github.com/bbernhard/signal-cli-rest-api/actions/runs/602885095

(The build job occasionally fails with an out of memory exception - still need to fix that somehow. So don't be surprised if it fails at some point; I'll kick off another one in that case. After it's finished there should be a new image available at dockerhub)

**Comment by mdegat01** [comment]
@bbernhard it works! I tried to register my phone with the new addon. Before I got this response every time:
```json
{
    "error": "WARN App - WARNING: Support for new group V2 is disabled, because the required native library dependency is missing: libzkgroup\nERROR App - Missing required native library dependency: libsignal-client\n"
}
```
Now I get the proper response:
```json
{
    "error": "Captcha required for verification, use --captcha CAPTCHA\nTo get the token, go to https://signalcaptchas.org/registration/generate.html\nCheck the developer tools (F12) console for a failed redirect to signalcaptcha://\nEverything after signalcaptcha:// is the captcha token.\n"
}
```

I can go through the process of actually getting the captcha and registering the number and testing the other APIs if you want full confirmation but it seems pretty clear the libraries are loading correctly now. I was hoping to avoid kicking my other addon off the number but I can if other APIs have additional dependencies that can't be tested otherwise.

**Comment by haberda** [comment]
I will update to the latest again and allow you to test from the repo once @bbernhard posts a new release. BTW, @mdegat01 I just run a local version of the git repo with the latest tag much like you just did in order to test. When I am satisfied something works for me I just push the working tag up to the repo. If you wanted to continue to run it locally you can run whatever version you want. 

However, in order to move over you either have to:
1) Start from scratch
2) Have a way to move the state file over to the new container folder (basically copy the contents of the add-on folder from the repo to the local instance)

In order to do 2 you have to have access to the file-system by either: running a supervised version of HASS, running a VM with access to the FS, enabling [SSH access to the host](https://developers.home-assistant.io/docs/operating-system/debugging/), or you can plug your RPI into a monitor and keyboard and access the console.

**Comment by bbernhard** [comment]
Thanks for testing! Version 0.36 is now on dockerhub.

**Comment by haberda** [comment]
@mdegat01 Add-on is updated. If it works for you feel free to close. Thanks for helping to troubleshoot.

**Comment by denics** [comment]
@haberda I am installing it right now on a vanilla HassOS. I keep you posted. One question, why can't we register the phone number from the configuration tab?

**Comment by denics** [comment]
I have an issue with the captcha. I tried all combinations possible but...

- curl -X POST -H "Content-Type: application/json" -d '{"captcha":"{signalcaptcha://...}"}' 'http://xxx:8080/v1/register/+0012345678'
{"error":"Invalid captcha given.\n"}
- curl -X POST -H "Content-Type: application/json" -d '{"captcha":"{...}"}' 'http://xxx:8080/v1/register/+0012345678'
{"error":"Invalid captcha given.\n"}
- curl -X POST -H "Content-Type: application/json" -d '{"captcha":"..."}' 'http://xxx:8080/v1/register/+0012345678'
{"error":"Invalid captcha given.\n"}
- curl -X POST -H "Content-Type: application/json" -d '{"captcha":"signalcaptcha://..."}' 'http://xxx:8080/v1/register/+0012345678'
{"error":"Invalid captcha given.\n"}

**Comment by haberda** [comment]
@denics I think you just have the syntax of the captcha incorrect. From the docs:
`curl -X POST -H "Content-Type: application/json" -d '{"captcha":"{captcha value}"}' 'http://127.0.0.1:8080/v1/register/<number>`

The "{captcha value}" part only contains the captcha value. Not the {} nor the signalcaptcha://

So if your captcha looks like: 
`signalcaptcha://03AGdBq278luH54P2dbLhegQfM7PpQi6DJcbxCE-IuTV1BCkG2wqn9Njl2KuEB`

Then the registration would look like:
`curl -X POST -H "Content-Type: application/json" -d '{"captcha":"03AGdBq278luH54P2dbLhegQfM7PpQi6DJcbxCE-IuTV1BCkG2wqn9Njl2KuEB"}' 'http://127.0.0.1:8080/v1/register/<number>`

> One question, why can't we register the phone number from the configuration tab?

Two reasons: First this is just a reproduction of a docker container which is maintained by another dev; packaged for HASSIO. Second, I am not a developer, I just like to tinker with stuff and figured out how to do the first thing. So I don't really know how to do what you suggest. If you know how, feel free to submit a pull request.

**Comment by mdegat01** [comment]
Gonna assume denics issue was resolved there or another issue will be opened and close this out since this one is resolved. Thanks for all the help!
