### ISSUE TITLE
Permissions issue when updating profile in signal addon

### ISSUE THREAD

**Issue by mdegat01** [haberda/hassio_addons#20]
After getting the addon updated on the latest version I tried to run this command to update my profile so I could use v2 groups (with everything actually filled out):
```bash
curl -X PUT -H "Content-Type: application/json" -d '{"base64_avatar": "", "name": "Home Assistant"}' 'http://[ip-address]:8080/v1/profiles/[phonenumber]'
```
When I did I got this error in response:
```json
{
    "error": "INFO SignalAccount - Config file is in use by another instance, waiting…\nINFO SignalAccount - Config file lock acquired.\nUpdate profile error: /data/avatars\n"
}
```
After trying a few variations I gave up and went into the actual docker image. I followed these on-login directions to try and use the `signal-cli` directly
```
WARNING: signal-cli-rest-api runs as signal-api (not as root!)
Run 'su signal-api' before using signal-cli!
If you want to use signal-cli directly, don't forget to specify the config directory. e.g: "signal-cli --config /data/data"
```
As an aside, there's a bug in these directions. When inside the image I found you actually have to run `signal-cli --config /data` for it to find your existing config, not `/data/data`.

Anyway from there I tried to do `updateProfile` via the cli directly and got this (number removed):
```bash
signal-api@1315902c-signal-messenger:/data/data$ signal-cli --config /data -u NUMBER updateProfile --name "Home Assistant" --avatar /share/ha_icon.png
Update profile error: /data/avatars (Permission denied)
```
I decided as a test to see what happened if I ignored the directions and ran the command as root instead of as `signal-api`. This worked fine and now my profile and groups are all updated.

So it looks like there's a permissions issue with the `signal-api` user the container uses. In order to update the profile it needs permission to create the `/data/avatars` folder and then create/update files inside it in the form of `/data/avatars/profile-NUMBER`.

**Comment by mdegat01** [comment]
Note that I originally posted this on an issue in the Signal CLI Rest API container and bbernhard had [this comment](https://github.com/bbernhard/signal-cli-rest-api/issues/96#issuecomment-787042182) about it. Thought it might help with the fix.

**Comment by haberda** [comment]
For now I updated the docker file to use chown /data rather than /data/data. Solves this particular issue. You can refresh the repository and then click rebuild if it doesn't recognize the update.

For the next release there will be an environment variable that will solve it, but that container hasn't been pushed yet.

**Comment by mdegat01** [comment]
Yep looks like that resolved it. Thanks!
