### ISSUE TITLE
Signal addon snapshot size is enormous (~160mb)

### ISSUE THREAD

**Issue by mdegat01** [haberda/hassio_addons#22]
I have my system setup to snapshot everything nightly. I realized the other night that my snapshot size had climbed drastically so I started looking into why. I very quickly realized it was the signal addon as you can see:
<img width="394" alt="Screen Shot 2021-03-13 at 9 43 00 AM" src="https://user-images.githubusercontent.com/2037026/111033711-98899b00-83e0-11eb-86ac-e44866d353c9.png">

There's a couple other large ones in there that I have to look into but the signal addon's snapshot footprint is as big as the next 3 biggest combined. It's also especially confusing because this addon really doesn't have any data. For the other 3 large addons I had clear explanations
- Adguard Home and Visual Studio both have large files in `/data` that then get included
- Loki is one I am developing locally. For local addons HA snapshots the entire image not just `/data` since you may have changed the Dockerfile so its including the large Loki binary file

When I look in the signal container, the only large things are not in `/data`. These are the large things:
```
root@1315902c-signal-messenger:/# find . -size +9999k
./opt/signal-cli-0.8.0/bin/signal-cli-native
./opt/java/openjdk/lib/modules
./opt/java/openjdk/lib/server/libjvm.so
./tmp/signal-cli-0.8.0.tar
./usr/bin/signal-cli-rest-api
```
I wouldn't really expect any of these to be in the snapshot which suggests HA doesn't like how this addon is constructed and so is snapshotting the entire container. Perhaps this is its default behavior if an addon does not build from one of the [base images](https://github.com/home-assistant/docker-base)?

At the very least can trim it down a little by clearing out `/tmp`. I don't really know if there's any easy way to trim it down further then that but wanted to get this out there since it is a bit of an issue how large the snapshot is.

**Comment by mdegat01** [comment]
Also when I was doing the `find` I noticed a few other large things in `/share`. Obviously these had nothing to do with this addon, they were just large files I had put in `/share`. But up to this point I hadn't realized the Signal addon was even mapping `/share`.

It looks like it's mapping `/share` as read/write and `/ssl` as read-only. What's the reason for that? What does the addon use those folders for? I've used it a bit now and I thought it was entirely self-contained. There's not even any configuration options available, normally addons looking at `/ssl` have cert and key file options.

**Comment by haberda** [comment]
Hey @mdegat01.

In terms of the mapping of /share and /ssl; those are legacy and can be removed. I used to store the state file in /share and left it there for backward compatibility. However, that was before I really released it to anyone and I no longer attempt to copy the state file from /share to /data anyway. As far as /ssl goes, also legacy from when I was learning by copying. I have removed both on my local instance without issue, and the next release won't have those mappings.

The size of the container is a function of the upstream container. I can clear out /tmp which will free about 20mb. Actually, reading the upstream dockerfile it looks like an attempt is made to clear /tmp but it probably fails. For now, I will work on an update that at least clears /tmp.

All of the other items you found are binaries/libraries that make the container work. signal-cli is java I believe, hence the java libraries, and the rest-api is what makes it accessible. 

Believe it or not, the container used to be >500mb.

**Comment by mdegat01** [comment]
Wow, that's huge. Just to clarify, I'm not actually suggesting those files need to be deleted, I understand they are required for functionality. 

What I'm trying to figure out is why they need to be in the snapshot since they are just set up on container creation by the docker file. Notice the size of the other addon snapshots, some as small as 0mb. It's not that those have literally nothing in the container, it's that HA is recognizing that it only needs to capture what is in `/data` and not all the binaries and stuff setup automatically. I'm not sure what makes those addons different so HA is able to recognize that for those but not for this one.

**Comment by haberda** [comment]
Gotcha.

I think I know why it's this way, but it's just a theory. Normally, hassio addons are fully built images that reside on docker hub. This one on the other hand pulls the upstream base image and then locally builds the container from a Dockerfile (hence the 'Rebuild' button in the Supervisor). So I think what is happening is hassio backs up the base image and Dockerfile so it can rebuild it locally, rather than just backing up the link to docker hub.

I have little to no experience with docker hub, but I might know enough to get it working. Give me a couple hours (or maybe a day) to test it out.

**Comment by mdegat01** [comment]
@haberda I updated to the latest one to test out the dockerhub change but now I can't start the addon. When I try I get this in the supervisor logs:
```
21-03-14 00:30:13 ERROR (SyncWorker_5) [supervisor.docker] Image eightiesguy/signal-addon not exists for addon_1315902c_signal_messenger
```
I do actually see that image on dockerhub so its weird. Think there's a caching issue or something?

**Comment by haberda** [comment]
Odd. It installed fine over my install. It might be a cache issue, but I don't understand why that would be. It's as if it is not pulling the image from docker hub yet trying to launch it anyway. Try rebooting, etc to see if that helps.

Also it seems like you have access to the folder where the files are stored right? If so, you can just copy the contents, delete the addon and reinstall, then restore the folder. That might be the easiest way. If nobody else has issues, this is honestly a better way forward.

**Comment by mdegat01** [comment]
Yea that's what I did. Was a little bit of a process but got it done. I uninstalled it and reinstalled it which got it starting fine. Then I copied the data back over. Had a bit of an issue when I restarted after that, the addon seemed to be unable to shut down cleanly. I tried to kill it manually and got an error about being unable to release a mount? Rebooting the host cleared it up, back up and running now.

**Comment by mdegat01** [comment]
And looks like that did the trick! Here's the size of the addon snapshot footprint now (have also been putting in work shrinking up the others too):
<img width="363" alt="Screen Shot 2021-03-13 at 8 07 43 PM" src="https://user-images.githubusercontent.com/2037026/111054117-e1b90980-8437-11eb-8272-64c3bb2e7929.png">
Thanks @haberda!

**Comment by haberda** [comment]
Very good, glad to hear and glad to help!

Now I need to do the same treatment to these other add-ons...
