### ISSUE TITLE
"eightiesguy/signal-addon does not exist" error

### ISSUE THREAD

**Issue by ronaldt80** [haberda/hassio_addons#23]
I upgraded v. 0.36.1 tot 0.36.3 - since the upgrade I can not start the plugin, supervisor logs shows the following error:

`21-03-14 12:22:07 ERROR (SyncWorker_2) [supervisor.docker] Image eightiesguy/signal-addon not exists for addon_1315902c_signal_messenger`

I run odroid n2+ / hass os 5.12 - could it be the image needs a tag? Eg. eightiesguy/signal-addon:0.36.3 vs. eightiesguy/signal-addon?

thanks!

**Comment by ronaldt80** [comment]
Rolled back to 0.36.1 which works fine; alternatively, could it be the system architecture? I run aarch64 if I am not mistaken

**Comment by haberda** [comment]
Stay rolled back for now. I will be updating the README in a little bit to address this issue.

**Comment by AlexanderBabel** [comment]
Hey, I have the same issue.

@ronaldt80 How did you do a rollback?

**Comment by haberda** [comment]
README is updated. You have to have a snapshot to roll back. It's not all that bad to update to the latest, but it is not painless.

I didn't have this issue on my local systems when I pushed the test update otherwise I would have put out a warning first.

**Comment by ronaldt80** [comment]
many thanks!
