### ISSUE TITLE
Signal: Tested "Another method"

### ISSUE THREAD

**Issue by LiJu09** [haberda/hassio_addons#25]
Tried update addon using "Another method" and it works, no more than 10 minutes. Its probably faster and easier then removing sdcard. It shoud be first option.

**Comment by haberda** [comment]
Thank you for testing. I will update the Readme!

**Comment by jorojoro66** [comment]
Can someone explain in more detail how to replace the 'data' folder? I tried to follow the instruction under the addon, but cannot get it working.

**Comment by LiJu09** [comment]
I assume you got snapshot of old and new version of addon.

Open old and new snapshot with 7-zip.
In both snapshots go to "." -> "1315902c_signal_messenger.tar.gz" -> "1315902c_signal_messenger.tar"
Take drag data folder from old to new shapshot place it in free space in 7-zip window (not data folder).
Confirm copying of files.
Close new shapshot file.
Confirm update of archives (It will ask two times).
Remove new snapshot from home assistant.
Upload new updated snapshot.
"Restore the new Frankenstein snapshot"

Hope it will help. :wink:
If you get it working, let me know.

**Comment by jorojoro66** [comment]
Exactly what I did in PeaZip, tried in 7-zip now with the same negative result.
After restoring the Frankenstein snapshot Signal addon is back to version 0.36.1 instead of 0.36.3 and not working.
I must be copying the wrong file or to the wrong place, but followed your instructions. The only difference I see is that I was only asked one time for confirmation when updating archives....
Hope you can give me an extra hint.

**Comment by LiJu09** [comment]
What version of addon you got in `snapshot.json` in new Frankenstein snapshot?
```
  "addons": [
    {
      "slug": "1315902c_signal_messenger",
      "name": "Signal Messenger",
      "version": "0.36.3",
      "size": 0.0
    }
  ]
```

**Comment by jorojoro66** [comment]
"addons": [
    {
      "slug": "1315902c_signal_messenger",
      "name": "Signal Messenger",
      "version": "0.36.3",
      "size": 0.02
    }
  ]

**Comment by LiJu09** [comment]
And when you restore it you got 0.36.1?

**Comment by jorojoro66** [comment]
yes

**Comment by LiJu09** [comment]
And did you uninstalled addon before restoring?

**Comment by jorojoro66** [comment]
Nope, just updated. Will try uninstall first now

**Comment by jorojoro66** [comment]
Can at least start Signal again now, but get error when shooting a message.
2021-03-18 17:09:14 ERROR (SyncWorker_46) [homeassistant.components.signal_messenger.notify] process killed as timeout reached
2021-03-18 17:09:14 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall notify.signal_notification (c:bd8342934424b7d0546719764e0b08f7): message=(message removed by me, private....)>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1504, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1523, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/notify/__init__.py", line 154, in _async_notify_message_service
    await self.async_send_message(**kwargs)
  File "/usr/src/homeassistant/homeassistant/components/notify/__init__.py", line 133, in async_send_message
    await self.hass.async_add_executor_job(partial(self.send_message, message, **kwargs))  # type: ignore
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/signal_messenger/notify.py", line 79, in send_message
    raise ex
  File "/usr/src/homeassistant/homeassistant/components/signal_messenger/notify.py", line 76, in send_message
    self._signal_cli_rest_api.send_message(message, self._recp_nrs, filenames)
  File "/usr/local/lib/python3.8/site-packages/pysignalclirestapi/api.py", line 83, in send_message
    raise exc
  File "/usr/local/lib/python3.8/site-packages/pysignalclirestapi/api.py", line 79, in send_message
    raise SignalCliRestApiError(json_resp["error"])
pysignalclirestapi.api.SignalCliRestApiError: process killed as timeout reached

**Comment by LiJu09** [comment]
And what is in addon log?

**Comment by jorojoro66** [comment]
Now I'm lost. It's back to 0.36.1 without me doing anything.... I will start over again

**Comment by jorojoro66** [comment]
Seems that my number registration in Signal got lost now. Afraid I have to install Signal from scratch

**Comment by LiJu09** [comment]
Uninstall everything, and try it once again.
And before restoring uninstall it.

I also checked sending message and I cant send it
`[GIN] 2021/03/18 - 11:42:36 | 400 |  8.963424414s |   192.168.0.114 | POST     "/v2/send"`
There is wrong someting else.

**Comment by jorojoro66** [comment]
I even cant get back to the previous version now. 

HA-log file:
ERROR App - User +----------- is not registered. (----------- = my phone number sending the messages)

**Comment by LiJu09** [comment]
You got same number registered in addon and in mobile app?

**Comment by jorojoro66** [comment]
No, have two numbers, one to send from and one to receive. Always worked perfect

**Comment by jorojoro66** [comment]
Just did a complete reboot. That solved my error and registration issue and everything working as before. But still on 0.36.1 now, no idea how to upgrade to a working 0.36.3

**Comment by LiJu09** [comment]
Make snapshot of that version. Uninstall it. Install new version. Make snapshot. Uninstall it. Download both to your computer and remove it from home assistant. Move that data folder. Upload it to home assistant and restore it.

**Comment by LiJu09** [comment]
Did you removed snapshot of new addon before uploading that Frankenstein snapshot?

**Comment by jorojoro66** [comment]
Yes, I did. Will try the whole process again soon. Spent too much time already today.

**Comment by LiJu09** [comment]
But now I cannot send any message `[GIN] 2021/03/18 - 13:34:27 | 400 | 18.721414039s |     172.30.32.1 | POST     "/v2/send"`
That status 400

**Comment by LiJu09** [comment]
So I reinstalled addon from scratch configured mobile number, groups..., then made snapshot of that working 0.36.3, uninstalled, installed again, made snapshot of it without any data, uninstalled, moved data folder from working 0.36.3 to that one without data, removed all addon snapshots from home assistant, uploaded new "Frankenstein" snapshot, restored, and now it works.

**Comment by haberda** [comment]
I would suggest that when you restore the Franken snapshot that you restore it on top of a blank 0.36.3. So the process would be:

- Snapshot 0.36.1
- Download 0.36.1 snapshot to your computer
- Delete 0.36.1 add-on
- Install 0.36.3
- Make snapshot of 0.36.3 and download to your computer, do not delete 0.36.3 add-on
- Build Frankenstein snapshot of data from 0.36.1 into 0.36.3
- Restore Frankenstein snapshot on top of 0.36.3

If you have trouble with the snapshot method, taking out the SD card may be the best route. Thanks @LiJu09 for helping.

**Comment by jorojoro66** [comment]
I must be doing something wrong copying the file from snapshot 36.1 to snapshot 36.3. Tried again and again after restoring the 36.3 snapshot I’m back to 36.1

**Comment by jorojoro66** [comment]
Just gave it a last try. As far as I know I did exactly the same as before, but looks like it’s working now. Thanks for your support.

**Comment by ronaldt80** [comment]
works well! many thanks!
