### ISSUE TITLE
HACS Repository issue

### ISSUE THREAD

**Issue by blaze31b** [haberda/hassio_addons#26]
when attempting to add the custom repository to HACKS the following error is triggered: " Repostitory structure for master is not compliant"

**Comment by haberda** [comment]
This is a repository for Home Assistant add-ons, it is not a HACS repository.

**Comment by blaze31b** [comment]
Aah! That makes sense, Thanks for clearing it up, I'm still a bit of a noob at HA. Awesome add-on btw.
