### ISSUE TITLE
Addon 0.37 fails on send a message

### ISSUE THREAD

**Issue by dreem2001** [haberda/hassio_addons#28]
Hello.

After upgrade to 0.37 I face the error
`Unexpected error for call_service at pos 1: WARN App - WARNING: Support for new group V2 is disabled, because the required native library dependency is missing: libzkgroup Missing required native library dependency: libsignal-client`

**Comment by speedst3r** [comment]
Yep, native mode doesn't want to work on arm64.

Suggest that native mode is exposed as an option so it can be enabled/disabled at will?

**Comment by poudenes** [comment]
I have same issue. After the update I got this error also.


```
Version | core-2021.3.4
-- | --
Installation Type | Home Assistant Supervised
Development | false
Supervisor | true
Docker | true
Virtual Environment | false
Python Version | 3.8.7
Operating System Family | Linux
Operating System Version | 5.4.79-v8+
CPU Architecture | aarch64
Timezone | Europe/Amsterdam
```

**Comment by haberda** [comment]
Reverting Native mode to be off. 0.37.1 will be up in a moment.

**Comment by haberda** [comment]
Sorry about that wasn't aware of the issue and I can only test so much. I'll try and get an option working.

**Comment by haberda** [comment]
0.36.2 now has an option for Native mode

**Comment by poudenes** [comment]
Already updated 4 min ago... worked 👯
