### ISSUE TITLE
Can't update Signal addon without rebooting

### ISSUE THREAD

**Issue by mdegat01** [haberda/hassio_addons#29]
For the last couple updates of the Signal add-on I've been unable to update the add-on cleanly. It lets me update but when I try to start it again I get a message like this in my supervisor logs:
```
21-03-23 17:48:47 ERROR (SyncWorker_8) [supervisor.docker] Can't create container from addon_1315902c_signal_messenger: 409 Client Error for http+docker://localhost/v1.40/containers/create?name=addon_1315902c_signal_messenger: Conflict ("Conflict. The container name "/addon_1315902c_signal_messenger" is already in use by container "a58845cf67ed6c093a01a7c93d264c8bfc2f3b4e0a51bdaaa76205f040c0b353". You have to remove (or rename) that container to be able to reuse that name.")
```
Also when I do a `docker ps -a` I see this:
```
CONTAINER ID   IMAGE                                                  COMMAND                  CREATED          STATUS                    PORTS                      NAMES
a58845cf67ed   eightiesguy/signal-addon:0.37                          "/entrypoint.sh"         19 hours ago     Removal In Progress                                  addon_1315902c_signal_messenger
```
This doesn't go away either. Even if I try a `docker rm -f a58845cf67ed` I just get this:
```
Error response from daemon: container a58845cf67ed6c093a01a7c93d264c8bfc2f3b4e0a51bdaaa76205f040c0b353: driver "overlay2" failed to remove root filesystem: unlinkat /mnt/data/docker/overlay2/b3093222e8e7feefba8e63a05c3456d48a9eda4dca9b56909c1ec5a2f57733d3/merged: device or resource busy
```
The only way I've been able to fix it is by rebooting the host after an update. Which works but its pretty disruptive.

No other add-ons I have do this and I've updated many of them recently so I think its something about this one. I think it just started happening since changing to image so maybe its related to that?

Sorry for not reporting this sooner. Some issues were to be expected with the change to the new image so I gave it a pass. But it happened with 0.37 and now happened again with 0.37.1 so it seems like something is wrong at this point.

**Comment by haberda** [comment]
I don't get this error, but I get something similar about it not being able to clean up the old image. I am not sure why, but I will investigate it. I think even if I find a solution it will still happen on the next update because it's baked into the cake on the current image install.

**Comment by haberda** [comment]
I think I figured it out. The Supervisor uses two separate methods to identify the container tag, one the docker hub tag, the other a tag placed in the dockerfile when the image is built. In order to cleanly update it needs both tags, but it only needs the first tag to work as it has been. This solved my issue anyway.

Because this fix is built into the image, the next update will probably have the same issue, but after that it should be a clean update. 

If you want to test if it actually worked, I already rebuilt the 0.37.1 image to have this built in. If you take a snapshot, then use portainer (there's an addon) or the cli (if you are on Supervised install and are good with cli) you can delete the cached 0.37.1 image, when you reinstall it will pull the updated 0.37.1. That way when you install the next update it should be a clean upgrade.

**Comment by mdegat01** [comment]
Ok I just tried the portainer thing. Up and running again now, will let you know how it goes with the next update.

**Comment by mdegat01** [comment]
Just tried to update to 0.37.2 and got the same error when I pressed start
```
21-03-25 00:50:43 ERROR (SyncWorker_5) [supervisor.docker] Can't create container from addon_1315902c_signal_messenger: 409 Client Error for http+docker://localhost/v1.40/containers/create?name=addon_1315902c_signal_messenger: Conflict ("Conflict. The container name "/addon_1315902c_signal_messenger" is already in use by container "4f937ec5c8aedf9d081a4b0386af09d996f5a3966a1e15dac8f3b36b513ad88b". You have to remove (or rename) that container to be able to reuse that name.")
```

**Comment by haberda** [comment]
I cannot reproduce the issue. I have three home-assistant instances setup on 3 all three supported archs. All of them upgrade fine now that I embedded the version as a label in the image.

In terms of your issue, I have found several other add-ons where people report very similar errors:

https://github.com/mKeRix/room-assistant/issues/202

https://community.home-assistant.io/t/hass-io-cant-create-container-from-addon/129792

They seem to suggest that an old container is stuck in there and has to be forced deleted. In the second link the solution was to use Portainer to delete the offending image. One of the commenters brings up the point that you have to un-hide the images in the Portainer add-on to see them all. I forgot about that step. In Portainer->Settings->Hidden Containers you can un-hide all the containers. I don't know if it will help, but as I said I can't reproduce so I don't know what else to suggest.

If you see any images or containers in there older than 0.37.2, delete them. The old images should be cleaned up fine going forward with my fix. 

It may be worth backing up the folder with the Signal data and deleting everything Signal with Portainer. Then restore the folder and reinstall the add-on.

**Comment by mdegat01** [comment]
Forgot about this, sorry for leaving it open so long. Fwiw I do still see this issue with some regularity but I have also seen it with other addons (albeit significantly less frequently). This makes me think that rather then being an issue with this addon its probably an issue with either supervisor or my system and perhaps exacerbated (but not caused) by something about this addon.

Considering it is extremely difficult to debug and reproduce but has a very easy workaround (reboot the machine) I'm just going to close it. Will revisit if I find out any new information or a clear reproduction path.
