### ISSUE TITLE
Can't install emby server 

### ISSUE THREAD

**Issue by Gangol** [haberda/hassio_addons#30]
Log:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0. [s6-init] ensuring user provided files have correct perms...exited 0. 
[fix-attrs.d] applying ownership & permissions fixes... 
[fix-attrs.d] done. 
[cont-init.d] executing container initialization scripts... 
[cont-init.d] done. 
[services.d] starting services 
[services.d] done. 
[cmd] sed exited 0 
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening [cont-finish.d] executing container finish scripts... 
[cont-finish.d] done. 
[s6-finish] waiting for services. 
[s6-finish] sending all processes the TERM signal.

**Comment by haberda** [comment]
Hello,

What computer platform are you using? Are you using a 64 bit OS?

**Comment by haberda** [comment]
There was a build problem for arm processors. It should be resolved. Let me know if not.

**Comment by Gangol** [comment]
Raspberry pi 4
Hassio 32 bit

**Comment by Gangol** [comment]
Fixed thank you
