### ISSUE TITLE
Health check error

### ISSUE THREAD

**Issue by andriej** [haberda/hassio_addons#31]
In log files, during Supervisor health check, I see:
```
Apr 23 10:32:16 brix hassio-supervisor[4030]: #033[32m21-04-23 08:32:16 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token#033[0m
Apr 23 10:34:47 brix dockerd[593]: time="2021-04-23T10:34:39.331644253+02:00" level=error msg="stream copy error: reading from a closed fifo"
Apr 23 10:34:47 brix dockerd[593]: time="2021-04-23T10:34:39.331656131+02:00" level=error msg="stream copy error: reading from a closed fifo"
Apr 23 10:34:47 brix dockerd[593]: time="2021-04-23T10:34:39.335771439+02:00" level=warning msg="Health check for container 5b1ce5d62db79275ed3aeeb73b40b2fec788514d19e84cb477ad42035414a0a4 error:
Apr 23 10:34:49 brix systemd[1]: run-docker-runtime\x2drunc-moby-5b1ce5d62db79275ed3aeeb73b40b2fec788514d19e84cb477ad42035414a0a4-runc.TjkTsq.mount: Succeeded.
```

Not sure why, but it seems to cause other errors (I/O?) regarding... InfluxDB addon (which is reporting errors and dropped events in HA).

**Comment by haberda** [comment]
I assume this is Signal?

I really have no idea how or why it would interfere with Influx. I run both without any issue.

If you use the dockercli or portainer what is the status of the container? It should say healthy.

**Comment by andriej** [comment]
Both of them were healthy and working. 
I did upgrade my Debian underneath (10.8->10.9) and rebooted, issue has gone.
