### ISSUE TITLE
Video Playback in Gallery

### ISSUE THREAD

**Issue by panhans** [haberda/hassio_addons#34]
Hi there,

video playback is missing in gallery. There are no preview pictures and video playback doesnt work.
Maybe we need ffmpeg codec in this image.

Thanks!

**Comment by haberda** [comment]
Hello,

Are you talking about Emby? There are several addons hosted here. What do you mean by video playback in gallery? 

Most of the addons here are just repackaged docker containers that don't necessarily directly interact with Home Assistant.
