### ISSUE TITLE
could you support i386 in the manifest

### ISSUE THREAD

**Issue by amritgary** [haberda/hassio_addons#35]
Would you be able to include arch=i386?

**Comment by haberda** [comment]
Perhaps. For which add-on? It depends on what is available upstream.

**Comment by amritgary** [comment]
This is for the nextcloud add-on

**Comment by haberda** [comment]
Unfortunately the upstream [docker container](https://hub.docker.com/r/linuxserver/nextcloud) I use for this is only amd64, arm64 and arm. To support i386 would mean I would have to find another container to adapt.

**Comment by amritgary** [comment]
Thanks for looking. I was able to use  [Home Assistant NextCloud Addon with i386 support](https://github.com/joaudfo/hassio-addons/tree/master/nextcloud)
