### ISSUE TITLE
[Nextcloud] Cant implement to Hassio via iframe due to X-Frame-Options

### ISSUE THREAD

**Issue by MisterT87** [haberda/hassio_addons#37]
Big Thanks first of all for this Hassio Addon ! :)
But like title says... 

I tried several workarounds but nothing worked (also tried different Browser). Is it possible to fix this and maybe with the possibility to configure it in the addon configurations menu in hassio ?

See Also: [IFrame Solution](https://return2.net/nextcloud-enable-external-iframe/)

P.S.: Can I Update nextcloud inside docker (From update notifications) ?
Will it persists addon restarts ? or should I only update nextcloud over hassio addons (This docker image) ?

**Comment by haberda** [comment]
Hi. I will look into a fix for this, but you should be able to follow the instructions you sent. To do so (assuming you are using HassOs), you can install the Portainer add-on from the community repo and then use that to access the shell of the Nextcloud add-on and follow the instructions you provided. I will be traveling for a few weeks soon and probably won't get to looking at it for a little while.

In terms of updates, what Nextcloud is actually doing is installing itself to the persistent storage that Hass-io provides (aka the /data folder). Because of this, you actually have to update the way you suggest. Updates to the add-on only effect the Nextcloud version of a newly installed instance. This is just the way Nextcloud works. So when I push an update, all that is really being updated are the underlying container resources, not Nextcloud itself.

**Comment by MisterT87** [comment]
Thanks, yeah I already tried to fix but without success...
maybe it has something to do with nginx in docker container - I cant isolate which is the right way...

tried (alone) the solution from the URL above and tried to manipulate nginx config all without success - Im done with my experience ;)
I am not a docker expert to get this

**Comment by MisterT87** [comment]
hm I tried again - I have no clue really.

I am almost sure you cant fix this issue because this docker image runs in default network mode (host mode) in docker.
Maybe there is a better chance in bridged network mode.

man such webservices with nginx proxy into docker is a real pain in the *** :/

**Comment by MisterT87** [comment]
@haberda Sorry for tripple posting, but I got it !
The Problem was I had disabled x-frame-options in nextcloud config to test nginx config first - but You cant disable x-frame-options in nextcloud (firefox wont recognize it !!)

The docker network mode was NOT the problem also NOT nginx config file ->
so TLDR: DONT TOUCH nginx config or network mode - both are already fine

You only need to change nextcloud config to get it working ! (tested with firefox 90 and microsoft edge 92 (chromium) )

Implementation suggestion (for addon configuration in HassOS):

- create a new configuration part above network (I would name it "nextcloud config")
- under nextcloud config: create to forms - both forms with + and - for adding multiple domains (+ stands for add; - for remove)
- first form: name it "allowed Frame Domains" and allow the following input: "https://mydomain.local:8123/page1 (for example)
- 2nd form: name it: "allowed Frame Ancestors" and allow the following input: "https://mydomain.local:8123/page1/* (for example)
**NOTE: * = Wildcards are really important in 2nd form - please dont forget**

Both Forms should add a new line in `/lib/public/AppFramework/Http/ContentSecurityPolicy.php` for  `$allowedFrameDomains` and `$allowedFrameAncestors` and please be patient: **the input from both forms need to be inside  ' '  - See IFrame Solution above.**

I would also suggest to add a seperate note on the Github readme for this Addon ->
allowed Frame Domains: Here you only setup which source domains are allowed to embed website - example: `https://domain.local:8123 `

allowed Frame Ancestors: Here you only setup which ancestors are allowed to embed - example: `https://domain.local:8123/nextcloud` or `https://domain.local:8123/*`
**Note1: dont touch previous settings already in this php file just add inputs from the forms with a newline**

**! Note2: You need to specify the port number on both forms - because Hassio listening to port 8123 and https:// w/o port number will be redirected to port 443 !**

**Note3: You also must setup these settings on local network - even if you embed also a local network domain**

**!! Note4: Dont try to make automatic scripts to make it easier for some users -> tldr: its not possible (some routers you can override all your local domain names !!**
`#END`

So I hope I could help you out for implementation ? :) 
On my side: fixed and working now !

I leave this issue open if you have questions about the settings, or if you have other questions you need described deeply - 
If you got everything right from this tutorial and dont have questions -> just close the issue :)

Hope I could help :)

**Comment by haberda** [comment]
Thanks! This is great. I'll test this out sometime soon, like I said I'll be traveling for some time so it will be a little hard for me to look at this for a few weeks.

**Comment by MisterT87** [comment]
yeah no prob @haberda 
can you make a pre release if youre finished to implement ? So that all hassio's dont recogize the update and I can retest your implementation to check syntax and config changes...

If I should test your implementation - then hightlight me here after releasing pre-release please :)

**Comment by haberda** [comment]
My testing repository is located [here](https://github.com/haberda/hassio_addons_edge). I'll post here when a test version with these changes is available there.

**Comment by haberda** [comment]
So, looking back at your comment here; it seems that this is highly dependent on the domain you wish to allow. It would therefore be difficult to make generic enough to implement.

Nextcloud has a ton of options like this that are best configured by occ. There are two methods to do that, a WebUI app, and via the portainer add-on. 

If you are any good at bash feel free to send me a script and I'll try and wire it up to some config options, but for maintainability I try and shy away from too many config options when there are alternatives.

**Comment by MisterT87** [comment]
Yep maybe didnt test the portainer thing - I am the guy who likes harended server systems and I use as less web UI stuff when possible (reducing surface attacks from outside) ;)

Other topic: I have insufficent time for now - for which (even If I wrote a script for it) I cant update / maintain it later also...
And you can be pretty sure I have to maintain also the shell script for it - coz nextcloud is updating ton of stuff hourly ;)

for now I agree your opinion also :D
but thank you for lookin for it :)
