### ISSUE TITLE
Updating Trusted Domain

### ISSUE THREAD

**Issue by A-Yamout** [haberda/hassio_addons#43]
The WebOCC has been discontinued and I find no other way to change or add trusted domains could you please help.

**Comment by haberda** [comment]
If webOCC is disconnected then you have to access the console of the container. To do that on hassos you can install the portainer add-on from the community add-ons repository, it will allow you to access the console. Once there just follow the official documentation from Nextcloud.

**Comment by A-Yamout** [comment]
Thank you 🙏
