### ISSUE TITLE
OCC web issues

### ISSUE THREAD

**Issue by RowdyRagamuffin** [haberda/hassio_addons#44]
Hi just running Nextcloud on HA and the occweb won't load with the following error. Any ideas?

Internal Server Error

The server was unable to complete your request.

If this happens again, please send the technical details below to the server administrator.

More details can be found in the server log.
Technical details

    Remote Address: 
    Request ID: lsdJ2tZ4r0A2JnQH1RuR

**Comment by haberda** [comment]
OCC Web has not been updated to support the latest NC yet. If you need OCC then you have to access the add-on console. If you are on HASSOS then the only way to do that (without modifying the OS) is to use the Portainer add-on in the community add-ons store. It will allow access to the console in its web interface.

From there, you have to navigate to where OCC is located, here: `/data/config/www/nextcloud/`

After that just follow the NC documentation. You shouldn't need sudo to run any of the commands, so the command: `sudo -u www-data php occ status` to get the current status would reduce to `occ status`.

**Comment by RowdyRagamuffin** [comment]
Thanks! Figured it out with the portainer console! I consider this one closed as it is working fine. Cheers

**Comment by haberda** [comment]
Glad to help!

**Comment by pazz** [comment]
Does this still work for you?

I cannot execute occ in the container from the current image:

```console
root@db21ed7f-nextcloud-ocr:/root# sudo -u www-data php /data/config/www/nextcloud/occ status
sudo: unknown user: www-data
sudo: error initializing audit plugin sudoers_audit
root@db21ed7f-nextcloud-ocr:/root# sudo -u 1000 php /data/config/www/nextcloud/occ status
sudo: unknown user: 1000
```

**Comment by pazz** [comment]
It seems this user exists though:

```console
root@db21ed7f-nextcloud-ocr:/# grep 1000 /etc/passwd
guest:x:405:1000:guest:/dev/null:/sbin/nologin
abc:x:1000:1000::/config:/bin/false
```

**Comment by pazz** [comment]
Ah! of course! the user is called `abc`, so this works:

```console
sudo -u abc php /data/config/www/nextcloud/occ status
```
