### ISSUE TITLE
[Transmission] openvpn_config file

### ISSUE THREAD

**Issue by hulkhaugen** [haberda/hassio_addons#48]
Sorry for this n00b question, but VPN is new to me. I created a OpenVPN.net account, so I have a username, password and a Subscription Key. Now, you're asking for a .ovpn file, and from my googling, that's seems to be a standard for several VPN services, but I can't seem to find anywhere to get a hold of this file for my setup. Is it part of a paid subscription, or is it something I can make myself with the sub key?

~~Bonus question: Is there any way to customize the "incomplete" folder location?~~
EDIT: This is apparently set in my Remote Client App.

**Comment by haberda** [comment]
To your first question, you should get an ovpn file from your vpn provider, if they offer that method. Some providers do not. I have used NordVPN and privateinternetaccess with this add-on.

Seems like you basically figured out the second question but I will give you a fair warning: the incomplete folder will be reset if you restart the add-on. I forked this add-on some time ago, so the original work was not mine, I just fixed some stuff that broke with the VPN support. The was it's setup, the incomplete is hard-coded in the initialization script. I can change it by making it an option you can set in the next release, but it will be some time before I can get to it.

**Comment by hulkhaugen** [comment]
Thanks for that note, cheers!
