### ISSUE TITLE
Nextcloud - Unable to add trusted domain

### ISSUE THREAD

**Issue by djansen1987** [haberda/hassio_addons#49]
When i try to add the OCC Web to add trusted domain i get the following error:

Client error: `GET https://git.adphi.net/attachments/85ad9b45-2227-475c-86a4-96c8ab60a3e0` resulted in a `404 Not Found` response: <!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-sca (truncated...)

Setup:
Nextcloud for Home Assistant
Current version: 23.0.0

Home Assistant 2022.2.8
supervisor-2022.01.1
core-2022.2.8
Home Assistant OS 7.4

![image](https://user-images.githubusercontent.com/20375973/154488088-39a1f845-4200-426d-a94b-37b41d2e8dfe.png)

**Comment by haberda** [comment]
OCCWeb was deprecated by the maintainer.

Try the instructions here:
https://github.com/haberda/nextcloud-addon/tree/main/nextcloud
