### ISSUE TITLE
[Nextcloud] add /media directory to shared paths

### ISSUE THREAD

**Issue by da-anda** [haberda/hassio_addons#5]
Hey,

it would be nice to add the `/media` share which is available since HA 0.115.0 to the nextcloud add-on in addition to `/share`. Thanks.

**Comment by haberda** [comment]
Good idea. I'll update it.

**Comment by haberda** [comment]
I think it should be working, want to try?

**Comment by da-anda** [comment]
yes, working fine. I simply added /media as external folder so that I can also browse my media files in NC now 👍
