### ISSUE TITLE
How can delete data

### ISSUE THREAD

**Issue by DrArut** [haberda/hassio_addons#50]
Hello. How can delete files in attachment and data folders? I can't find path of add-on signal messenger in hassio. I use hassio os (alpine linux).

**Comment by haberda** [comment]
There is no direct way to access the filesystem on hassos. In my [Nextcloud instructions](https://github.com/haberda/hassio_addons/tree/master/nextcloud), it contains information you need to access the filesystem in the container, just change the container info to signal (or whatever). From there, all of the persistent data is stored in `/data/`.
