### ISSUE TITLE
Sending message to group - only me receives the message

### ISSUE THREAD

**Issue by migromao** [haberda/hassio_addons#53]
Hi,
I'm using the addon and register my phone.
sending messages to phone number works like a charm.
issue is when sending messages to groups.
My phone number is member of one group, I receive the message as sent by me, but no one else receives the message in the same group.
if I reply to the message , every one sees the reply but mentions the original message could not be found.
checking info of sent message, shows I have read the message and nothing else .. and the other members aren't even listed . If I send message from my phone , regular - everyone receives the message and info shows delivered and read list of the message.
Any troubleshooting I could take on this ?
btw - I'm able to send messages for every phone in that group without issues

**Comment by haberda** [comment]
Hello.
Just want to say off the bat that if there is an underlying issue with the Signal API then the [upstream](https://github.com/bbernhard/signal-cli-rest-api) project or even the project [upstream](https://github.com/AsamK/signal-cli) to that should be the place to go and report the issue(s). The add-on is just the upstream project with some modified environment variables to enable use in HASSIO.

That said, I have some questions to help narrow where the issue may be:
1) The group you are trying to message, are you using the Home Assistant integration to attempt sending the message, or the command line?
2) When you try and send the message, are there any messages displayed in the add-on log?
3) How were the group(s) setup? Did you use the API documented [here](https://bbernhard.github.io/signal-cli-rest-api/)?

**Comment by migromao** [comment]
Hi Haberda,
Thank you for the prompt reply.
on your questions 

1. The group you are trying to message, are you using the Home Assistant integration to attempt sending the message, or the command line?
I've tried via Home Assistant integration as this is my objective.

2. When you try and send the message, are there any messages displayed in the add-on log?
correct and my phone number in the group (its the sender as well) , receives the message.
in the logs of addon:
[GIN] 2022/04/22 - 00:35:30 | 200 |     124.293µs |  192.168.68.139 | GET      "/v1/about"
[GIN] 2022/04/22 - 00:35:41 | 201 | 11.319266119s |  192.168.68.139 | POST     "/v2/send"

3. How were the group(s) setup? Did you use the API documented [here](https://bbernhard.github.io/signal-cli-rest-api/)?
I've used the CLI documentation with curl commands to the addon port. It's working for my number (member of the group) and only others don't see the message

**Comment by migromao** [comment]
Hi Haberda,

sorted out the issue.
I've created the group but sent invite to members and although they accepted the invite, the addon failed to acknowledge it. 

Solution:
after I added the numbers as members ([following the documentation](https://bbernhard.github.io/signal-cli-rest-api/#/Groups/post_v1_groups__number___groupid__members)) they started receiving the messages from Home Assistant.
Thank you for your work on the addon

**Comment by haberda** [comment]
Very good, glad to hear it. Just my 2c but I prefer to define groups in Home Assistant (normal notify groups) rather than through the add-on. The only downside is there is not a common thread shared between members, but there have been a number of times that the upstream has broken groups and it became too painful to keep using for me.

**Comment by migromao** [comment]
I would definitely use the Home Assistant groups but it's not a common thread with all the members.
Thank you for your development :)
