### ISSUE TITLE
Request: Map Data volume outside HA backup

### ISSUE THREAD

**Issue by ykri** [haberda/hassio_addons#57]
Hi Haberda,

I am using your addon in HASSOS.
Would it be possible to map a Volume for Nextcloud Data, that is not backed up by Homeassistant, so that a Full Backup does not include Nextcloud data as well?

Thanks,

**Comment by haberda** [comment]
Unfortunately not. The only volumes HASSOS allows you to map are `/config` `/share` `/ssl` `/data` and `/media`. All of those are backed up with a full backup, and HASSOS does not allow anything else. I use another add-on that manages backups for me, and have it skip the `/share` folder.

I am considering adding the option to map a samba share in the container, however, this will only allow nextcloud to have access to it, it can't be the primary data storage location.

**Comment by ykri** [comment]
I guess then I 'll have to always do a partial backup excluding the folder /media where I have mapped my external HDD where my NC data are.

Thanks
