### ISSUE TITLE
Nextcloud upfate 24.0.3 -> 24.0.4 fail

### ISSUE THREAD

**Issue by ykri** [haberda/hassio_addons#59]
I updated Nextcloud addon, in HA (HASSOS on a RPi4), the version indicated in HA is 24.0.4 but the application is still at 24.0.3. Is there any issue in the image pulled by LinuxServer.io?

**Comment by haberda** [comment]
The way Nextcloud works is it 'installs' when you first install to a persistent storage. The linuxserver image version will only install the stated version when first installed. Nextcloud itself can be updated via the Nextcloud UI. Frankly, all updating the image does is update everything in the container that is not Nextcloud. So if you want the latest Nextcloud version, you have to update using the UI. There's plenty of Nextcloud documentation on how to update floating around out there but [here](https://docs.nextcloud.com/server/latest/admin_manual/maintenance/update.html)'s one that basically covers it.

The UI updater in Nextcloud kinda sucks and is finicky, you may also want to use command line updater if you're comfortable with that. You have to log into the container to do that, if you follow my basic guide on setting trusted domains, that has you logging into the container to set the domains, so you can start there.

**Comment by ykri** [comment]
Thank  you very much for the extensive response!
