### ISSUE TITLE
Nextcloud data folder change issue

### ISSUE THREAD

**Issue by alexbelgium** [haberda/hassio_addons#6]
To begin with, thanks very much for all your addons. They are great and are working perfectly for me! 

I have an issue : If I try to change the default data location folder, it fails with the message : "Can't create data directory or it can't be written to it".

I did some investigation if that can be of help. Sorry for the noob language - I'm learning ;-)
- It happens with all locations - it even fails with its own subdirectory like /share/nextcloud/test ; or /media/nextcloud
- I can create files manually in those same folders so it's should not be a question of write permissions (drwxr-xr-x) ?
- Looking into the nextcloud documentation it seems that it can happen if folders are not owned by the same instance as the nextcloud addon. By doing "ls -l" I see that the folders created with this addon are owned by the user "911" from the group "1001" (all my other folders are owned by root). I read on reddit that "911 is theID that linuxserver.io containers use when the PUID or PGID are not properly set or passed to the container." 

Config : rpi3b ; hassio 0.116 ; nextcloud addon 0.04

**Comment by haberda** [comment]
I'll look into this. Might be a few days

**Comment by alexbelgium** [comment]
Thanks. I found another way to do what i wanted by mounting my files on a smb accessed through nextcloud using the externak source app. Therefore i don't need anymore to change the data folder location. I'll close the issue but if you look into it, it could still further improve your addon for other users.
