### ISSUE TITLE
maintenance mode

### ISSUE THREAD

**Issue by KonstBr** [haberda/hassio_addons#61]
Hello,

I recently updated Nextcloud to 24.0.4. carried out.

Something went wrong. So it's now in maintenance mode.

How do I get this away?

When I type "docker ps" in the terminal it says "command not found"

thank you in advance

**Comment by haberda** [comment]
Hey sorry, hopefully you figured it out. Nextcloud updating is pretty sketchy in general so it it no surprise.

When you say terminal, do you mean the `SSH & Web Terminal` add-on? If so, you have to disable Protection Mode. But you're on the right track, you have to enter the Nextcloud container and turn off maintenance mode according to the Nextcloud documentation.
