### ISSUE TITLE
-Question- Signal: Get receiving messages? 

### ISSUE THREAD

**Issue by filikun** [haberda/hassio_addons#63]
I'm using the Signal addon with json-rpc mode and was wondering if there is any possibility to get receiving messages exposed to HA someway? Could be used for example actionable notifications of sorts.

**Comment by haberda** [comment]
If you look at the upstream project, there is an endpoint to listen for messages. It technically can probably be done in HA; but I haven't tried.

**Comment by Mincka** [comment]
Have a look there:
https://github.com/bbernhard/signal-cli-rest-api/discussions/305
