### ISSUE TITLE
How to: Install the add-on, choose your desired port, start.

### ISSUE THREAD

**Issue by squonk11** [haberda/hassio_addons#67]
I have a (probably terrible) newbie question: I think I was able to install the addon; at least I see it in the github entities of  homeassistant. In your manual you simply say: Install the add-on, choose your desired port, start. Assuming that I installed it correctly: how and where do I select the port and how and where do I start the addon? I only want to use the signal_messenger addon.

**Comment by haberda** [comment]
In the same UI that you installed the add-on from you can set ports and start the add-on. It has a default port of 8080, if you're good with that, then you can just start it. Once it's setup, you can use the internal docker network to send messages and don't need a port at all.

**Comment by squonk11** [comment]
Maybe I need to add that I am having a homeassistant core installation using a Python venv. So, there is no add-on store available. Maybe this is somehow the reason?

**Comment by squonk11** [comment]
when I enter this command on the console:
`curl -X POST -H "Content-Type: application/json" --data '{"use_voice": false}' 'http://127.0.0.1:8080/v1/register/+49...`
I get the error message:
`curl: (7) Failed to connect to 127.0.0.1 port 8080: Connection refused`
so, the  Signal Messenger REST API does not seem to be running...
Do you have any hint for me?

**Comment by squonk11** [comment]
> In the same UI that you installed the add-on from you can set ports and start the add-on. It has a default port of 8080, if you're good with that, then you can just start it. Once it's setup, you can use the internal docker network to send messages and don't need a port at all.

Unfortunately I can not find any dialog where I can set the port and/or start the add-on. Also, I am not using docker - docker is not installed on my Raspberrypi. Is there any other way to run this addon?

**Comment by squonk11** [comment]
I tried with ha ip address, but I get the same error message. I think the signal-cli is not running.
I can not work with add-ons because I did the core installation using a Python virtual environment. Also I do not have Docker installed. Maybe with my installation it is not possible to use Signal messenger?

**Comment by haberda** [comment]
If you are not running docker, then there is no way you are running this add-on. So frankly, I don't really know how to advise you.

**Comment by squonk11** [comment]
Thank you for your kind reply. I will try some more ideas I have. If one of these is successfull I will post the result here; if not, I will close this issue and use WhatsApp instead.

**Comment by ManfredS1965** [comment]
I have got the same problem with HAOS. I installed the addon, it is starting:

+ set -e
+ [ -z /data ]
+ usermod -u 1000 signal-api
usermod: no changes
+ groupmod -g 1000 signal-api
+ chown 1000:1000 -R /data
+ cat
+ cap_prefix=-cap_
+ cat /proc/sys/kernel/cap_last_cap
+ seq -s ,-cap_ 0 40
+ caps=-cap_0,-cap_1,-cap_2,-cap_3,-cap_4,-cap_5,-cap_6,-cap_7,-cap_8,-cap_9,-cap_10,-cap_11,-cap_12,-cap_13,-cap_14,-cap_15,-cap_16,-cap_17,-cap_18,-cap_19,-cap_20,-cap_21,-cap_22,-cap_23,-cap_24,-cap_25,-cap_26,-cap_27,-cap_28,-cap_29,-cap_30,-cap_31,-cap_32,-cap_33,-cap_34,-cap_35,-cap_36,-cap_37,-cap_38,-cap_39,-cap_40
+ [ normal = json-rpc ]
+ hostname+ awk {print $1}
 -I
+ export HOST_IP=172.30.33.7
+ exec setpriv --reuid=1000 --regid=1000 --init-groups --inh-caps=-cap_0,-cap_1,-cap_2,-cap_3,-cap_4,-cap_5,-cap_6,-cap_7,-cap_8,-cap_9,-cap_10,-cap_11,-cap_12,-cap_13,-cap_14,-cap_15,-cap_16,-cap_17,-cap_18,-cap_19,-cap_20,-cap_21,-cap_22,-cap_23,-cap_24,-cap_25,-cap_26,-cap_27,-cap_28,-cap_29,-cap_30,-cap_31,-cap_32,-cap_33,-cap_34,-cap_35,-cap_36,-cap_37,-cap_38,-cap_39,-cap_40 signal-cli-rest-api -signal-cli-config=/data
time="2023-02-06T10:09:06+01:00" level=info msg="Started Signal Messenger REST API"

Afterwards in a terminal session I get the error:

[core-ssh ~]$ curl -X POST -H "Content-Type: application/json" --data '{"use_voice": true}' 'http://127.0.0.1:8080/v1/register/+498142xxxxxxx'
curl: (7) Failed to connect to 127.0.0.1 port 8080 after 0 ms: Connection refused

**Comment by haberda** [comment]
You cannot use the loopback address unless you are logged into the console of the Signal container. Use the machine address.

**Comment by ManfredS1965** [comment]
TNX, that solved my problem. :-)
