### ISSUE TITLE
nextcloud: node.js?

### ISSUE THREAD

**Issue by hindseb** [haberda/hassio_addons#68]
Hi haberda,
Thanks a lot for creating the add-on nextcloud!
I successfully installed it and used it for a while. 

I want to use the app 'recognize' (https://github.com/nextcloud/recognize) within nextcloud to categorize/face recognize pictures. However, this app requires **Node.js.**
I am far from being an expert, but I googled many different ways to install node.js and tried them. But it is not possible.

I am wondering if it is related to the fact that nextcloud is installed via an add-on in HA. Do you know a trick on how to install it, or can you include it in this add-on? Any tip would be highly appreciated.

Best, Sebastian

**Comment by geigervlad** [comment]
Hi, maybe this will help:
- this addon is based on haberda docker-image of nextcloud itself(which by assumption has no node.js installed)
- You could install node.js in the docker-container by using `docker exec -it CONTAINER_NAME bash` but it will only be temporary

The only long term solution would be to change the docker image of the hassio addon in the config file.

Hope this helps :-)

**Comment by haberda** [comment]
I am trying to not deviate much from what the upstream container offers so that I can maintain this more easily. I do this as a hobby and don't have a lot of time to troubleshoot if issues arise. If enough people wanted node.js I might consider having it install in the container, but as of now I suggest you go the route of @geigervlad's suggestion.

**Comment by hindseb** [comment]
Thank you for responding.
I am happy to try out the temporary solution. But I am gonna be honest, I am not an expert on this. Would you mind sharing some more details on how I can install node.js in the docker-container?
Do I need to use SSH & Web Terminal and then enter `docker exec -it CONTAINER_NAME bash`? 
Where can I find the Container_Name?

Thanks a lot for your help in advance!
Best,  Sebastian

**Comment by haberda** [comment]
If you read the add-on documentation about how to add a trusted domain it describes how to enter the container. From there you can install whatever software you want with apt.

https://github.com/haberda/nextcloud-addon
