### ISSUE TITLE
Can't add repository

### ISSUE THREAD

**Issue by Eivind99** [haberda/hassio_addons#73]
***Disclaimer: I am a novice at Home Assistant and a complete GitHub noob***

I am trying to add the NextCloud add on, put I seem to struggle with the directions...
In /hassio/store, when I try to add a custom repository (trying a couple different links) I keep getting the following error message:
"https://github.com/haberda/nextcloud-addon/ is not a valid add-on repository".

I am running the newest (stable) Home Assistant OS on an Rpi 4 (8GB).

**Comment by Eivind99** [comment]
I am so sorry, I see now that it works like a charm using what I assume is the correct link: "https://github.com/haberda/hassio_addons".
I will just verify that I have no further questions before I close this, if I can?

**Comment by haberda** [comment]
Sure no problem. However, if you're looking for a nextcloud addon on, the one in the repository below has many more options and is more up to date: 

https://github.com/alexbelgium/hassio-addons

**Comment by Eivind99** [comment]
I don't know how I missed that in my initial search. Will definitely have a look, thank you!
More up to date and such is always great, and I see there is plenty of other interesting addons there too.

For what it is worth the installation seems to have gone by painlessly for your addon tho! The only issue I seem to be having is with the certificate, but I think I know why.
