### ISSUE TITLE
hassio_addons inside a docker container [FEATURE REQUEST]

### ISSUE THREAD

**Issue by mushuthecat** [haberda/hassio_addons#78]
Hello,

Since I was unable to use the "Pull Request" section, I would like to make my request here.

Many of us use Home Assistant in its Docker version, which is much more flexible and easy to deploy.

Unfortunately, the add-ons are currently not compatible with the Docker version of Home Assistant. Could you provide a container that contains your solutions? This would allow everyone to have a complete container ready for use with your various solutions and would also make your solutions compatible with Home Assistant Docker.

Thank you

Have a great day

**Comment by haberda** [comment]
If you are running docker you can just run whatever container you want, including what is available here. I don't think what you are asking for is technically feasible, and if it is, what you are suggesting is beyond my expertise.
