### ISSUE TITLE
How reach Addon CLI to register number from HASSOS

### ISSUE THREAD

**Issue by bromosky** [haberda/hassio_addons#8]
Hey there,

found this Add-On and would really like to use it with the Signal Integration. 
But I have no clue how to access or configure the commandline to do so. It seems like the configuration line inside of the AddOn UI is the wrong place, because the logs didn't changed.

So I would really appreciate your help, if you could tell me, how to configure your AddOn with HASSOS. How am I able to reach the API to do so and put in the right commands?

Thank you, Max :)

**Comment by haberda** [comment]
This add-on uses the Rest API. There is no CLI. It is just a reproduction of the Docker container the official docs, with the exception that all that needs to be done is installing the add-on.

https://www.home-assistant.io/integrations/signal_messenger/

or

https://github.com/bbernhard/signal-cli-rest-api/blob/master/doc/HOMEASSISTANT.md#register-phone-number

The command line in the instruction is on a local machine, not in the container. So you need a computer with a command line and Curl.

**Comment by bromosky** [comment]
Got that. It's working now. Will try to make it more clear in the HomeAssistant Docs and edit those, if you don't mind.

Thanks again!

**Comment by haberda** [comment]
I don't mind either way. The official docs are maintained by @bbernhard because this is just meant as an easier way to use their Docker image.
