### ISSUE TITLE
Signal messenger returns 400 but sends the message

### ISSUE THREAD

**Issue by bernji** [haberda/hassio_addons#80]
Hello,

I am using the current released version of the signal messenger. Everything runs ok but I noticed that when I can the notify service to send a message that the service call fails.
I digged a bit deeper and had a look at the logs of the addon and I noticed that the addon returns 400 when sending the message.

```
[GIN] 2023/10/27 - 21:15:07 | 200 |     342.533µs |    192.168.0.88 | GET      "/v1/about"
[GIN] 2023/10/27 - 21:15:10 | 200 |  3.328996763s |    192.168.0.88 | GET      "/v1/receive/xxxx"
[GIN] 2023/10/27 - 21:15:13 | 400 |  6.115538261s |    192.168.0.88 | POST     "/v2/send"
[GIN] 2023/10/27 - 21:15:27 | 200 |  2.702972658s |    192.168.0.88 | GET      "/v1/receive/xxxx"
```

I assume that the service fails because of that. The message is sent ok though. 
Can you please advise? Can I somehow see some more (debug) messages to find the problem?

**Comment by haberda** [comment]
I don't think the container has any additional logs you can turn on.

If the home assistant service says it's failing then my first instinct is there is something about your network that isn't quite right. What is the IP address you are sending the query to in home assistant? You should not use `127.0.0.1` if you are. The internal docker network or the machine address are preferable.

The upstream container was updated today, so I just built a new version, you could try that too.
