### ISSUE TITLE
CPU core always at 100%

### ISSUE THREAD

**Issue by Dunuin** [haberda/hassio_addons#81]
Hi,

Since 29th october I'm seeing heavy power consumption of my homeserver. I found out its the HomeAssistant VM where one of the two vCPUs is always at 100% utilization. Digging a bit deeper I found out its caused by the Signal Addon. Once I stop it everything is normal again. While its running the Hassio webUI it's always showing "Add-on CPU Usage 50.8 %".

I always do all the updates so maybe an update broke something but I didn't changed any configurations. Previously everything worked fine. These are the versions I am running:
Signal addon: 0.70.0
Core:  2023.11.2
Supervisor: 2023.11.3
Operating System: 11.1
Frontend: 20231030.2

Last successful message I received was also on the 29th october.

My configuration.yaml looks like this:
```
# Signal Messenger
notify:
  - name: signal
    platform: signal_messenger
    url: "http://192.168.42.78:8080" # the URL where the Signal Messenger REST API is listening
    number: "+49123456789" # the sender number
    recipients: # one or more recipients
      - "+49987654321"
```

This is the Signal config:
```
mode: json-rpc
AUTO_RECEIVE: "true"
SIGNAL_CLI_CMD_TIMEOUT: 60
```

The logs are showing:
```
+ set -e
+ [ -z /data ]
+ usermod -u 1000 signal-api
usermod: no changes
+ groupmod -g 1000 signal-api
+ chown 1000:1000 -R /data
+ cat
+ cap_prefix=-cap_
+ cat /proc/sys/kernel/cap_last_cap
+ seq -s ,-cap_ 0 40
+ caps=-cap_0,-cap_1,-cap_2,-cap_3,-cap_4,-cap_5,-cap_6,-cap_7,-cap_8,-cap_9,-cap_10,-cap_11,-cap_12,-cap_13,-cap_14,-cap_15,-cap_16,-cap_17,-cap_18,-cap_19,-cap_20,-cap_21,-cap_22,-cap_23,-cap_24,-cap_25,-cap_26,-cap_27,-cap_28,-cap_29,-cap_30,-cap_31,-cap_32,-cap_33,-cap_34,-cap_35,-cap_36,-cap_37,-cap_38,-cap_39,-cap_40
+ [ json-rpc = json-rpc ]
+ /usr/bin/jsonrpc2-helper
time="2023-11-15T14:59:19+01:00" level=info msg="Found number  and added it to jsonrpc2.yml"
+ service supervisor start
Starting supervisor: supervisord.
+ supervisorctl start all
+ hostname -I
+ awk {print $1}
+ export HOST_IP=172.30.33.4
+ exec setpriv --reuid=1000 --regid=1000 --init-groups --inh-caps=-cap_0,-cap_1,-cap_2,-cap_3,-cap_4,-cap_5,-cap_6,-cap_7,-cap_8,-cap_9,-cap_10,-cap_11,-cap_12,-cap_13,-cap_14,-cap_15,-cap_16,-cap_17,-cap_18,-cap_19,-cap_20,-cap_21,-cap_22,-cap_23,-cap_24,-cap_25,-cap_26,-cap_27,-cap_28,-cap_29,-cap_30,-cap_31,-cap_32,-cap_33,-cap_34,-cap_35,-cap_36,-cap_37,-cap_38,-cap_39,-cap_40 signal-cli-rest-api -signal-cli-config=/data
time="2023-11-15T14:59:21+01:00" level=info msg="Started Signal Messenger REST API"
time="2023-11-15T14:59:22+01:00" level=error msg="Couldn't read data for number : EOF. Is the number properly registered?"
time="2023-11-15T15:04:22+01:00" level=error msg="Couldn't read data for number : EOF. Is the number properly registered?"
time="2023-11-15T15:09:22+01:00" level=error msg="Couldn't read data for number : EOF. Is the number properly registered?"
time="2023-11-15T15:14:22+01:00" level=error msg="Couldn't read data for number : EOF. Is the number properly registered?"
[GIN] 2023/11/15 - 15:16:48 | 200 |    1.681153ms |   192.168.42.78 | GET      "/v1/about"
[GIN] 2023/11/15 - 15:16:48 | 400 |    1.101498ms |   192.168.42.78 | POST     "/v2/send"
time="2023-11-15T15:19:22+01:00" level=error msg="Couldn't read data for number : EOF. Is the number properly registered?"
```

**Comment by haberda** [comment]
It looks like your registration file was corrupted somehow. You can restore a backup, or delete it and re-register.

**Comment by haberda** [comment]
I think this issue is the same as this one: https://github.com/bbernhard/signal-cli-rest-api/issues/340#issue-1580309733

You can try the fix mentioned there, or wait for the next upstream release.

**Comment by Dunuin** [comment]
> I think this issue is the same as this one: [bbernhard/signal-cli-rest-api#340 (comment)](https://github.com/bbernhard/signal-cli-rest-api/issues/340#issue-1580309733)
Could you give me a hint how I can edit the config file at "signal-cli-config/data/<some random id>" via shell?

**Comment by haberda** [comment]
You either have to ssh into the home assistant host, or use something like the Advanced SSH & Web Terminal add-on to get to the file. In the SSH add-on you can use docker commands to access the shell of the Signal add-on; the process is similar to [here](https://github.com/haberda/hassio_addons/blob/master/nextcloud/README.md) replacing nextcloud with signal. It should drop you in the right folder.

 I think if you just run the normal mode rather than json-rpc mode it should work though. The only real difference is speed in sending the messages. Normal mode takes ~2-3 seconds to send.
