### ISSUE TITLE
No connection to the signal server, when connecting a device and when registering a new phone number

### ISSUE THREAD

**Issue by sebastian2012** [haberda/hassio_addons#83]
Hi!
I have installed the addon according to the instructions: added the repository to Homeassistant, installed and started the addon. The addon is running smoothly so far. However, when I try to register a new phone number using curl and provide the captcha, I receive an error message stating that the captcha is invalid. Additionally, when attempting to connect an existing Signal connection from a smartphone by scanning the QR code, the smartphone displays an error message indicating an invalid operation. Manually logging into the Docker container via SSH and running ping (after a manual installation) shows that the container can access the internet in principle. Registering the phone number via the command line using signal-cli also fails with the same error
message. Does anyone have any ideas regarding this issue?

Best Regards!

**Comment by haberda** [comment]
Two quick questions:
1. Any chance you are using 127.0.0.1 rather than the machine address? Your last point makes it seem like probably not. 
2. Are you running normal mode? To register you should be.

There's more documentation and support available at the [upstream](https://github.com/bbernhard/signal-cli-rest-api) project.

**Comment by sebastian2012** [comment]
Hi!
1. I run the curl-Commands from my Notebook, not from the Homeassistant-Instances. ... I think, that's work way not?
2. 2. Yes I have choose normal and other Modes, nothing works ... :-)

**Comment by haberda** [comment]
Well, right now the upstream is broken, but when the update comes out, if you're still having an issue, I'd check with the upstream. I have a feeling though that your issue may be related to the upstream issue. Basically Signal changed something and the fix has not flowed down stream yet.

**Comment by sebastian2012** [comment]
Hi,
I have know updated to Version 0.81.0, but Device-Linking and or the new Registration doesn't work ... same problems ...

**Comment by owcazz** [comment]
I have a similar problem.
signal_messenger add-on for HA installed.
When adding Use your existing mobile phone number,
generates a QR code.
When I scan the QR code on my phone, it says registered and nothing happens.
The new device you added doesn't appear in the phone app.

**Comment by haberda** [comment]
I don't think this is a function of the add-on. This is just a repackaging of an upstream docker container. If there is a technical issue with registering I would suggest asking for support with the upstream projects.

**Comment by sebastian2012** [comment]
Hi!
Know I have write some Informations in the Upstream Project in this bug:
https://github.com/bbernhard/signal-cli-rest-api/issues/443
Do you use the Docker-Container from bbernhard?

**Comment by haberda** [comment]
Yes, this add-on is just the bbernhard Docker image with an additional script to set some environment variables.
