### ISSUE TITLE
Addon suddenly stopped working, no connection to local server

### ISSUE THREAD

**Issue by bobbolous** [haberda/hassio_addons#84]
Today out of nowhere I stopped receiving signal messages.
I did not change anything on the HAss server side or signal side.
I checked if I could send messages directly through the cli I receive the following:
```
curl -X GET -H "Content-Type: application/json" 'http://127.0.0.1:8080/v1/qrcodelink?device_name=HomeAssistant'
curl: (7) Failed to connect to 127.0.0.1 port 8080 after 0 ms: Couldn't connect to server
```
Around the same time this issue here appeared:
https://github.com/bbernhard/signal-cli-rest-api/issues/475

and that points to this issue:
https://github.com/AsamK/signal-cli/issues/1439

**Comment by alfwro13** [comment]
yep, same problem here

**Comment by haberda** [comment]
Signal changed something that broke the CLI. An update from the upstream project is required. When the upstream fix is available I will issue an update. Also see: [120](https://github.com/haberda/signal-addon/issues/120)

**Comment by haberda** [comment]
> Today out of nowhere I stopped receiving signal messages. I did not change anything on the HAss server side or signal side. I checked if I could send messages directly through the cli I receive the following:
> 
> ```
> curl -X GET -H "Content-Type: application/json" 'http://127.0.0.1:8080/v1/qrcodelink?device_name=HomeAssistant'
> curl: (7) Failed to connect to 127.0.0.1 port 8080 after 0 ms: Couldn't connect to server
> ```
> 
> Around the same time this issue here appeared: [bbernhard/signal-cli-rest-api#475](https://github.com/bbernhard/signal-cli-rest-api/issues/475)
> 
> and that points to this issue: [AsamK/signal-cli#1439](https://github.com/AsamK/signal-cli/issues/1439)

Also, those curl commands are not failing because the noted issue. Those are failing because you are using the localhost address which will only work inside the container. You need to use your home assistant machine's IP address instead of 127.0.0.1

**Comment by bobbolous** [comment]
Thanks for pointing that out.
Just for reference, now I receive this error:
```
curl -X GET -H "Content-Type: application/json" 'http://homeassistant.local:8080/v1/qrcodelink?device_name=HomeAssistant'
{"error":"Couldn't create QR code: no data to encode"}
```

**Comment by derjoerg** [comment]
Hi @haberda,
can you update the signal-messenger addon to the latest release 0.81 to fix the current issues?

**Comment by haberda** [comment]
Fix is published

**Comment by bobbolous** [comment]
Works! Thank you!
