### ISSUE TITLE
The current machine does not support all of the following CPU features

### ISSUE THREAD

**Issue by plord12** [haberda/hassio_addons#85]
With todays update, 0.82.0, I'm seeing :

```
pysignalclirestapi.api.SignalCliRestApiError: The current machine does not support all of the following CPU features that are required by the image: [FP, ASIMD, AES, PMULL, SHA1, SHA2, CRC32, LSE, DCPOP, SHA3, SHA512, SVE, PACA, SVEBITPERM, SVE2].
Please rebuild the executable with an appropriate setting of the -march option.
```

I'm running on a fully managed Odroid-C2

**Comment by plord12** [comment]
I rolled back to 0.81.0 (by restoring from backup).

**Comment by haberda** [comment]
This is an [upstream](https://github.com/bbernhard/signal-cli-rest-api/issues/510#issue-2222020096) issue I believe.

**Comment by plord12** [comment]
Thanks.  Looks like the upstream has been fixed ... do we need a new plugin release to pick it up ?

**Comment by haberda** [comment]
The upstream has not released a production fix yet. I'll update the add-on after 0.83 is released.

**Comment by plord12** [comment]
Brilliant, thanks !

**Comment by haberda** [comment]
0.83 is now released. It should fix the issue.
