### ISSUE TITLE
Unable to start Signal Addon due to lack of configuration on 1st attempt

### ISSUE THREAD

**Issue by owldown** [haberda/hassio_addons#86]
- Installed the Addon
- Clicked Start to start the add on
- "Go to configuration" pops up with "value must be one of ['json-rpc', 'native', 'normal']" and buttons for CANCEL and EDIT CONFIG
- Click EDIT CONFIG
- switched to Configuration tab, which reads "This add-on has no configuration"

If editing the config is required, how do I do that?

Log shows nothing, add-on is not started.

I tried uninstalling and reinstalling, and now there is a configuration tab with radio buttons. I chose json-rpc, and now the add-on starts. Not sure if this is a bug or a fluke, but it didn't work as expected the first time.

**Comment by haberda** [comment]
Yeah, not sure. But sounds like it's working now.
