### ISSUE TITLE
"Finish linking on your other device"

### ISSUE THREAD

**Issue by gunarser** [haberda/hassio_addons#88]
The issue is described here in detail: https://github.com/bbernhard/signal-cli-rest-api/issues/564
It looks like the mentioned fix needs to be incorporated into the HA Addon as well.

**Comment by ge8020** [comment]
Sorry to comment this, but what is the fix for this problem? I´m using 0.88 and the problem is still existent for me, so why is this issue closed?

**Comment by gunarser** [comment]
As for me, the add-on update solved the issue - I was able to link the HA instance to my Signal account.
Perhaps you are hitting different issue.

> Sorry to comment this, but what is the fix for this problem? I´m using 0.88 and the problem is still existent for me, so why is this issue closed?

**Comment by ge8020** [comment]
> As for me, the add-on update solved the issue - I was able to link the HA instance to my Signal account. Perhaps you are hitting different issue.
> 
> > Sorry to comment this, but what is the fix for this problem? I´m using 0.88 and the problem is still existent for me, so why is this issue closed?

Thank you for the Info. I am already on the latest Version of the addon, just installed it today.
I will have to look further...

**Comment by ge8020** [comment]
Still the same problem here:
I installed the latest addon (0.88), configured it as json-rpc (or "normal", "native", makes no difference).
Got me a qr code via "http://192.168.xxx.xxx:8080/v1/qrcodelink?device_name=signal-api", scan the qr code on a already signal-registered smartphone and get the signal message to finish the linking on the other device.
Whats the problem? Are here any ports to forward?
@haberda  : Please help, i really would like to get rid of Telegram für notifying ;-) Any suggestions from your side?
