### ISSUE TITLE
Linking not possible with 0.88

### ISSUE THREAD

**Issue by ge8020** [haberda/hassio_addons#90]
Still the same problem here:
I installed the latest addon (0.88), configured it as json-rpc (or "normal", "native", makes no difference).
Got me a qr code via "http://192.168.xxx.xxx:8080/v1/qrcodelink?device_name=signal-api", scan the qr code on a already signal-registered smartphone and get the signal message to finish the linking on the other device.
Whats the problem? Are there any ports to forward on the router?
@haberda  : Please help, i really would like to get rid of Telegram für notifying ;-) Any suggestions from your side?

**Comment by haberda** [comment]
I can't do anything until the upstream releases an update.

**Comment by mag2bue** [comment]
I am experiencing the same issue. I can scan the QR code, and it takes me back to the device overview page on my mobile phone. However, the Home Assistant is not listed there.

**Comment by ge8020** [comment]
> I can't do anything until the upstream releases an update.
@haberda ->
Just noticed, that there was a 0.89 released a few hours ago:
[https://github.com/bbernhard/signal-cli-rest-api/releases/tag/0.89](url)
so there is a chance, that we get a new version of the addon soon?

**Comment by haberda** [comment]
0.89 is up

**Comment by ge8020** [comment]
> 0.89 is up

New Version works for me! Thank you!
